### PR TITLE
Fix item duplication bug

### LINKED ISSUE #14: item duplication
set up the bench like so:

image

move 90 gold ingots into the source material. result: a gold block, and the 90 ingots are now in the craft output, so you get a free gold block.

### PR DESCRIPTION
**Pull request by Niklp09**
Fixes #14 
Uses some code from https://github.com/fluxionary/minetest-crafting_bench, @fluxionary thankfully allowed this :).

- Improve item movement log messages
- Only allow one item per stack in the recipe field
- Adding a recipe doesn't take the items anymore
- Add LBM to move leftover items from >1 items big stacks to the craft output

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -115,13 +115,71 @@ minetest.register_node("crafting_bench:workbench",{
 	end,
 	on_blast = function(pos) end,
 	on_metadata_inventory_move = function(pos, from_list, from_index, to_list, to_index, count, player)
-		minetest.log("action", player:get_player_name().." moves stuff in workbench at "..minetest.pos_to_string(pos))
+		local meta = minetest.get_meta(pos)
+		local inv = meta:get_inventory()
+		local stack = inv:get_stack(to_list, to_index)
+		stack:set_count(count)
+		minetest.log("action", player:get_player_name().." moves "..stack:to_string().." in workbench at "..minetest.pos_to_string(pos))
```
Comment (SmallJoker) [inline init.lua]: This looks very hacky. What's the difference to what Minetest currently does?

File: init.lua [hunk 2]
```diff
@@ -115,13 +115,71 @@ minetest.register_node("crafting_bench:workbench",{
...
+
+		if to_list == "dst" then
+			return 0
+		elseif to_list == "rec" then
+			local meta = minetest.get_meta(pos)
+			local inv = meta:get_inventory()
+			local stack = inv:get_stack(from_list, from_index)
+			stack:set_count(1)
+			inv:set_stack(to_list, to_index, stack)
+			return 0
```
Comment (SmallJoker) [inline init.lua:143]: What's the difference to simply returning `1` here?

File: init.lua [hunk 3]
```diff
@@ -201,6 +259,26 @@ minetest.register_abm( {
...
+minetest.register_lbm({
+	name = "crafting_bench:cleanup_rec_inv",
+	label = "remove multiple-item-stacks from recipe inv",
+	nodenames = {"crafting_bench:workbench"},
+	run_at_every_load = false,
+	action = function(pos, node)
+		local meta = minetest.get_meta(pos)
+		local inv = meta:get_inventory()
+		for i, item in ipairs(inv:get_list("rec")) do
+			if not item:is_empty() and item:get_count() > 1 then
```
Comment (SmallJoker) [inline init.lua]: These two expressions are equivalent, hence one is not needed.

File: init.lua [hunk 4]
```diff
@@ -201,6 +259,26 @@ minetest.register_abm( {
 	end
 } )
 
+minetest.register_lbm({
```
Comment (SmallJoker) [inline init.lua:264]: Why exactly is this LBM needed? Would you please be so nice to add a comment in the code above?

File: init.lua (hunk 1 above)
Comment (Niklp09) [reply init.lua]: I'll remove this callback since there's no advantage by having it.

**Comment by SmallJoker** [comment]
Looks good and works. Will merge in a few days unless there are objections.
